spring:
  datasource:
    #url: jdbc:h2:tcp://localhost:9099/~/daou
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: omy
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level: #띄어쓰기 없음
    "[org.hibernate.SQL]": debug #띄어쓰기 2칸